name: Lint
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "bin/*"
  push:
    paths:
      - "bin/*"

jobs:
  lint:
    name: shellcheck & shfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: luizm/action-sh-checker@v0.2.2
    env:
      SHELLCHECK_OPTS: --external-sources
      SHFMT_OPTS: -d -i 2 -ci
